#!/bin/bash

echo -e " - Sourcing bash_commonrc."
alias edbash='vim ~/.bashrc'
alias srcbash='source ~/.bashrc'

#More LS Aliases
alias la='ls -A'
alias l='ls -CF'
alias killNode="ps -ef | grep node | awk '{ print $2 }' | xargs kill -9"

#alias cp='cp -iv'                           # Preferred 'cp' implementation
alias cp='cp -v'                           # Preferred 'cp' implementation
alias mv='mv -iv'                           # Preferred 'mv' implementation
alias mkdir='mkdir -pv'                     # Preferred 'mkdir' implementation
alias ll='ls -FGlAhp'                       # Preferred 'ls' implementation
cd() { builtin cd "$@"; ll; }               # Always list directory contents upon 'cd'


#Networking Aliases
alias myip='curl ip.appspot.com'                    # myip:         Public facing IP Address
alias netCons='lsof -i'                             # netCons:      Show all open TCP/IP sockets
alias flushDNS='dscacheutil -flushcache'            # flushDNS:     Flush out the DNS Cache
alias lsock='sudo /usr/sbin/lsof -i -P'             # lsock:        Display open sockets
alias lsockU='sudo /usr/sbin/lsof -nP | grep UDP'   # lsockU:       Display only open UDP sockets
alias lsockT='sudo /usr/sbin/lsof -nP | grep TCP'   # lsockT:       Display only open TCP sockets
alias ipInfo0='ipconfig getpacket en0'              # ipInfo0:      Get info on connections for en0
alias ipInfo1='ipconfig getpacket en1'              # ipInfo1:      Get info on connections for en1
alias openTCPPorts='sudo /usr/sbin/lsof -nP | grep TCP | grep LISTEN '   # lsockU:       Display only open UDP sockets
alias openPorts='sudo lsof -i | grep LISTEN'        # openPorts:    All listening connections
alias showBlocked='sudo ipfw list'                  # showBlocked:  All ipfw rules inc/ blocked IPs
alias unloadPG='sudo launchctl unload -w /Library/LaunchDaemons/com.edb.launchd.postgresql-9.4.plist' #Stop Posgtres from auto launching
alias loadPG='sudo launchctl load -w /Library/LaunchDaemons/com.edb.launchd.postgresql-9.4.plist' #Stop Posgtres from auto launching

#   ii:  display useful host related informaton
#   -------------------------------------------------------------------
    ii() {
        echo -e "\nYou are logged on ${RED}$HOST"
        echo -e "\nAdditionnal information:$NC " ; uname -a
        echo -e "\n${RED}Users logged on:$NC " ; w -h
        echo -e "\n${RED}Current date :$NC " ; date
        echo -e "\n${RED}Machine stats :$NC " ; uptime
        echo -e "\n${RED}Current network location :$NC " ; scselect
        echo -e "\n${RED}Public facing IP Address :$NC " ;myip
        #echo -e "\n${RED}DNS Configuration:$NC " ; scutil --dns
        echo
    }

#Git alias
alias g='git' #git alais

echo -e " - Finished sourcing bash_commonrc."
